codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        target: auto
        threshold: 0%

flags:
  rossum-mcp:
    paths:
      - rossum-mcp/
    carryforward: true
  rossum-agent:
    paths:
      - rossum-agent/
    carryforward: true
  rossum-agent-client:
    paths:
      - rossum-agent-client/
    carryforward: true
