---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: rossum-agent

spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
  dataFrom:
    - extract:
        key: tools-rossum-agent/rossum-agent
