/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description Check API health and dependencies.
     */
    get: operations["health_check_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Chats
     * @description List chat sessions for the authenticated user.
     */
    get: operations["list_chats_api_v1_chats_get"];
    put?: never;
    /**
     * Create Chat
     * @description Create a new chat session.
     */
    post: operations["create_chat_api_v1_chats_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{chat_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Chat
     * @description Get detailed information about a chat session.
     */
    get: operations["get_chat_api_v1_chats__chat_id__get"];
    put?: never;
    post?: never;
    /** Delete Chat */
    delete: operations["delete_chat_api_v1_chats__chat_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{chat_id}/commits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Chat Commits
     * @description List configuration commits made in a chat session.
     */
    get: operations["list_chat_commits_api_v1_chats__chat_id__commits_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{chat_id}/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Feedback */
    get: operations["get_feedback_api_v1_chats__chat_id__feedback_get"];
    /** Submit Feedback */
    put: operations["submit_feedback_api_v1_chats__chat_id__feedback_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{chat_id}/feedback/{turn_index}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Feedback
     * @description Remove feedback for a specific turn.
     */
    delete: operations["delete_feedback_api_v1_chats__chat_id__feedback__turn_index__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{chat_id}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Send Message
     * @description Send a message and stream the agent's response via SSE.
     *
     *     If a previous request is still running for this chat, it will be cancelled
     *     before starting the new one. Client disconnects are also detected and will
     *     cancel the running agent.
     */
    post: operations["send_message_api_v1_chats__chat_id__messages_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{chat_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel Message
     * @description Cancel a running agent request for a chat.
     */
    post: operations["cancel_message_api_v1_chats__chat_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/commands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Commands */
    get: operations["list_commands_api_v1_commands_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{chat_id}/files": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Files
     * @description List all files for a chat session.
     */
    get: operations["list_files_api_v1_chats__chat_id__files_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{chat_id}/files/{filename}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download File
     * @description Download a file from a chat session.
     */
    get: operations["download_file_api_v1_chats__chat_id__files__filename__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{chat_id}/report-to-slack": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Report To Slack */
    post: operations["report_to_slack_api_v1_chats__chat_id__report_to_slack_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ArgumentSuggestion
     * @description A suggested value for a slash command argument.
     */
    ArgumentSuggestion: {
      /** Value */
      value: string;
      /** Description */
      description: string;
    };
    /**
     * CancelResponse
     * @description Response for cancel operations.
     */
    CancelResponse: {
      /** Cancelled */
      cancelled: boolean;
    };
    /**
     * ChatDetail
     * @description Detailed chat session information.
     */
    ChatDetail: {
      /** Chat Id */
      chat_id: string;
      /** Messages */
      messages: components["schemas"]["Message"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Files */
      files: components["schemas"]["FileInfo"][];
    };
    /**
     * ChatListResponse
     * @description Response for listing chat sessions.
     */
    ChatListResponse: {
      /** Chats */
      chats: components["schemas"]["ChatSummary"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /**
     * ChatResponse
     * @description Response for chat creation.
     */
    ChatResponse: {
      /** Chat Id */
      chat_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * ChatSummary
     * @description Summary of a chat session for list responses.
     */
    ChatSummary: {
      /** Chat Id */
      chat_id: string;
      /** Timestamp */
      timestamp: number;
      /** Message Count */
      message_count: number;
      /** First Message */
      first_message: string;
      /** Preview */
      preview?: string | null;
      /** Summary */
      summary?: string | null;
    };
    /**
     * CommandInfo
     * @description Information about an available slash command.
     */
    CommandInfo: {
      /** Name */
      name: string;
      /** Description */
      description: string;
      /**
       * Argument Suggestions
       * @default []
       */
      argument_suggestions: components["schemas"]["ArgumentSuggestion"][];
    };
    /**
     * CommandListResponse
     * @description Response for listing available slash commands.
     */
    CommandListResponse: {
      /** Commands */
      commands: components["schemas"]["CommandInfo"][];
    };
    /**
     * CommitInfo
     * @description A configuration commit with its changes.
     */
    CommitInfo: {
      /** Hash */
      hash: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /** Message */
      message: string;
      /** User Request */
      user_request: string;
      /** Changes */
      changes: components["schemas"]["EntityChangeInfo"][];
    };
    /**
     * CommitListResponse
     * @description Response for listing config commits in a chat.
     */
    CommitListResponse: {
      /** Commits */
      commits: components["schemas"]["CommitInfo"][];
    };
    /**
     * CreateChatRequest
     * @description Request body for creating a new chat session.
     */
    CreateChatRequest: {
      /**
       * Mcp Mode
       * @default read-only
       * @enum {string}
       */
      mcp_mode: "read-only" | "read-write";
      /** @default default */
      persona: components["schemas"]["Persona"];
    };
    /**
     * DeleteResponse
     * @description Response for delete operations.
     */
    DeleteResponse: {
      /** Deleted */
      deleted: boolean;
    };
    /**
     * DocumentContent
     * @description Document content in a message.
     */
    DocumentContent: {
      /**
       * Type
       * @default document
       * @constant
       */
      type: "document";
      /**
       * Media Type
       * @constant
       */
      media_type: "application/pdf";
      /**
       * Data
       * @description Base64-encoded document data
       */
      data: string;
      /**
       * Filename
       * @description Original filename of the document
       */
      filename: string;
    };
    /**
     * EntityChangeInfo
     * @description A single entity change within a config commit.
     */
    EntityChangeInfo: {
      /** Entity Type */
      entity_type: string;
      /** Entity Id */
      entity_id: string;
      /** Entity Name */
      entity_name: string;
      /**
       * Operation
       * @enum {string}
       */
      operation: "create" | "update" | "delete";
    };
    /**
     * ErrorResponse
     * @description Standard error response.
     */
    ErrorResponse: {
      /** Detail */
      detail: string;
      /** Error Code */
      error_code?: string | null;
    };
    /** FeedbackListResponse */
    FeedbackListResponse: {
      /** Feedback */
      feedback: {
        [key: string]: boolean;
      };
    };
    /** FeedbackRequest */
    FeedbackRequest: {
      /** Turn Index */
      turn_index: number;
      /** Is Positive */
      is_positive: boolean;
    };
    /** FeedbackResponse */
    FeedbackResponse: {
      /** Turn Index */
      turn_index: number;
      /** Is Positive */
      is_positive: boolean;
    };
    /**
     * FileInfo
     * @description Information about a file in a chat session.
     */
    FileInfo: {
      /** Filename */
      filename: string;
      /** Size */
      size: number;
      /** Timestamp */
      timestamp: string;
      /** Mime Type */
      mime_type?: string | null;
    };
    /**
     * FileListResponse
     * @description Response for listing files in a chat session.
     */
    FileListResponse: {
      /** Files */
      files: components["schemas"]["FileInfo"][];
      /** Total */
      total: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description Response for health check endpoint.
     */
    HealthResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: "healthy" | "unhealthy";
      /** Storage Connected */
      storage_connected: boolean;
      /** Storage Backend */
      storage_backend: string;
      /** Version */
      version: string;
    };
    /**
     * ImageContent
     * @description Image content in a message.
     */
    ImageContent: {
      /**
       * Type
       * @default image
       * @constant
       */
      type: "image";
      /**
       * Media Type
       * @enum {string}
       */
      media_type: "image/jpeg" | "image/png" | "image/gif" | "image/webp";
      /**
       * Data
       * @description Base64-encoded image data
       */
      data: string;
    };
    /**
     * Message
     * @description A single chat message.
     */
    Message: {
      /**
       * Role
       * @enum {string}
       */
      role: "user" | "assistant";
      /** Content */
      content:
        | string
        | (
            | components["schemas"]["TextContent"]
            | components["schemas"]["ImageContent"]
          )[];
      /** Feedback */
      feedback?: boolean | null;
    };
    /**
     * MessageRequest
     * @description Request body for sending a message.
     *
     *     Supports text-only messages or multimodal messages with images and documents.
     *     For image messages, use the `images` field with base64-encoded image data.
     *     For document messages, use the `documents` field with base64-encoded PDF data.
     */
    MessageRequest: {
      /**
       * Content
       * @description Text content of the message
       */
      content: string;
      /**
       * Images
       * @description Optional list of images (max 5) to include with the message
       */
      images?: components["schemas"]["ImageContent"][] | null;
      /**
       * Documents
       * @description Optional list of PDF documents (max 5) to include with the message
       */
      documents?: components["schemas"]["DocumentContent"][] | null;
      /**
       * Rossum Url
       * @description Optional Rossum app URL for context
       */
      rossum_url?: string | null;
      /**
       * Mcp Mode
       * @description MCP mode to use for this message and all subsequent messages. If not specified, uses the chat's current mode.
       */
      mcp_mode?: ("read-only" | "read-write") | null;
      /** @description Agent persona to use for this message and all subsequent messages. If not specified, uses the chat's current persona. */
      persona?: components["schemas"]["Persona"] | null;
    };
    /**
     * Persona
     * @enum {string}
     */
    Persona: "default" | "cautious";
    /** ReportToSlackRequest */
    ReportToSlackRequest: {
      /**
       * Rossum Url
       * @description Optional Rossum app URL for context (queue, etc.)
       */
      rossum_url?: string | null;
    };
    /** ReportToSlackResponse */
    ReportToSlackResponse: {
      /** Chat Id */
      chat_id: string;
      /** Channel */
      channel: string;
      /** Slack Ts */
      slack_ts: string;
    };
    /**
     * TextContent
     * @description Text content in a message.
     */
    TextContent: {
      /**
       * Type
       * @default text
       * @constant
       */
      type: "text";
      /** Text */
      text: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * StepEvent
     * @description Event emitted during agent execution via SSE.
     *
     *     Extended thinking mode separates the model's internal reasoning from its final response:
     *     - "thinking": Model's chain-of-thought reasoning (from thinking blocks)
     *     - "intermediate": Model's response text before tool calls
     *     - "final_answer": Final response when no more tool calls needed
     */
    StepEvent: {
      /**
       * Type
       * @enum {string}
       */
      type:
        | "thinking"
        | "intermediate"
        | "tool_start"
        | "tool_result"
        | "final_answer"
        | "error";
      /** Step Number */
      step_number: number;
      /**
       * Content
       * @default null
       */
      content: string | null;
      /**
       * Tool Name
       * @default null
       */
      tool_name: string | null;
      /**
       * Tool Arguments
       * @default null
       */
      tool_arguments: {
        [key: string]: unknown;
      } | null;
      /**
       * Tool Progress
       * @default null
       */
      tool_progress: [number, number] | null;
      /**
       * Result
       * @default null
       */
      result: string | null;
      /**
       * Is Error
       * @default false
       */
      is_error: boolean;
      /**
       * Is Streaming
       * @default false
       */
      is_streaming: boolean;
      /**
       * Is Final
       * @default false
       */
      is_final: boolean;
      /**
       * Tool Call Id
       * @default null
       */
      tool_call_id: string | null;
      /**
       * Is Hook Output
       * @default false
       */
      is_hook_output: boolean;
      /**
       * Context Usage Fraction
       * @default null
       */
      context_usage_fraction: number | null;
    };
    /**
     * SubAgentProgressEvent
     * @description Event emitted during sub-agent execution via SSE.
     */
    SubAgentProgressEvent: {
      /**
       * Type
       * @default sub_agent_progress
       * @constant
       */
      type: "sub_agent_progress";
      /** Tool Name */
      tool_name: string;
      /** Iteration */
      iteration: number;
      /** Max Iterations */
      max_iterations: number;
      /**
       * Current Tool
       * @default null
       */
      current_tool: string | null;
      /** Tool Calls */
      tool_calls?: string[];
      /**
       * Status
       * @default running
       * @enum {string}
       */
      status:
        | "thinking"
        | "searching"
        | "analyzing"
        | "reasoning"
        | "running_tool"
        | "completed"
        | "running";
    };
    /**
     * SubAgentTextEvent
     * @description Event emitted when sub-agent streams text output via SSE.
     */
    SubAgentTextEvent: {
      /**
       * Type
       * @default sub_agent_text
       * @constant
       */
      type: "sub_agent_text";
      /** Tool Name */
      tool_name: string;
      /** Text */
      text: string;
      /**
       * Is Final
       * @default false
       */
      is_final: boolean;
    };
    /**
     * TaskSnapshotEvent
     * @description Event emitted when task tracker state changes via SSE.
     */
    TaskSnapshotEvent: {
      /**
       * Type
       * @default task_snapshot
       * @constant
       */
      type: "task_snapshot";
      /** Tasks */
      tasks: {
        [key: string]: unknown;
      }[];
    };
    /**
     * AgentQuestionItemSchema
     * @description A single question within an agent question event.
     */
    AgentQuestionItemSchema: {
      /** Question */
      question: string;
      /** Options */
      options?: components["schemas"]["QuestionOptionSchema"][];
      /**
       * Multi Select
       * @default false
       */
      multi_select: boolean;
    };
    /**
     * QuestionOptionSchema
     * @description A single option for an agent question.
     */
    QuestionOptionSchema: {
      /** Value */
      value: string;
      /** Label */
      label: string;
      /**
       * Description
       * @default
       */
      description: string;
    };
    /**
     * AgentQuestionEvent
     * @description Event emitted when the agent asks the user a structured question.
     */
    AgentQuestionEvent: {
      /**
       * Type
       * @default agent_question
       * @constant
       */
      type: "agent_question";
      /** Questions */
      questions: components["schemas"]["AgentQuestionItemSchema"][];
    };
    /**
     * FileCreatedEvent
     * @description Event emitted when a file is created and stored.
     */
    FileCreatedEvent: {
      /**
       * Type
       * @default file_created
       * @constant
       */
      type: "file_created";
      /** Filename */
      filename: string;
      /** Url */
      url: string;
    };
    /**
     * SubAgentTokenUsageDetail
     * @description Token usage breakdown for sub-agents.
     */
    SubAgentTokenUsageDetail: {
      /** Input Tokens */
      input_tokens: number;
      /** Output Tokens */
      output_tokens: number;
      /** Total Tokens */
      total_tokens: number;
      /**
       * Cache Creation Input Tokens
       * @default 0
       */
      cache_creation_input_tokens: number;
      /**
       * Cache Read Input Tokens
       * @default 0
       */
      cache_read_input_tokens: number;
      /** By Tool */
      by_tool: {
        [key: string]: components["schemas"]["TokenUsageBySource"];
      };
    };
    /**
     * TokenUsageBreakdown
     * @description Token usage breakdown by agent vs sub-agents.
     */
    TokenUsageBreakdown: {
      total: components["schemas"]["TokenUsageBySource"];
      main_agent: components["schemas"]["TokenUsageBySource"];
      sub_agents: components["schemas"]["SubAgentTokenUsageDetail"];
    };
    /**
     * TokenUsageBySource
     * @description Token usage for a specific source (main agent or sub-agent).
     */
    TokenUsageBySource: {
      /** Input Tokens */
      input_tokens: number;
      /** Output Tokens */
      output_tokens: number;
      /** Total Tokens */
      total_tokens: number;
      /**
       * Cache Creation Input Tokens
       * @default 0
       */
      cache_creation_input_tokens: number;
      /**
       * Cache Read Input Tokens
       * @default 0
       */
      cache_read_input_tokens: number;
    };
    /**
     * StreamDoneEvent
     * @description Final event emitted when streaming completes.
     */
    StreamDoneEvent: {
      /**
       * Type
       * @default done
       * @constant
       */
      type: "done";
      /** Total Steps */
      total_steps: number;
      /** Input Tokens */
      input_tokens: number;
      /** Output Tokens */
      output_tokens: number;
      /**
       * Cache Creation Input Tokens
       * @default 0
       */
      cache_creation_input_tokens: number;
      /**
       * Cache Read Input Tokens
       * @default 0
       */
      cache_read_input_tokens: number;
      /** @default null */
      token_usage_breakdown:
        | components["schemas"]["TokenUsageBreakdown"]
        | null;
      /**
       * Max Input Tokens
       * @default 0
       */
      max_input_tokens: number;
      /**
       * Context Usage Fraction
       * @default 0
       */
      context_usage_fraction: number;
      /**
       * Config Commit Hash
       * @default null
       */
      config_commit_hash: string | null;
      /**
       * Config Commit Message
       * @default null
       */
      config_commit_message: string | null;
      /**
       * Config Changes Count
       * @default 0
       */
      config_changes_count: number;
    };
    /**
     * SSEEvent
     * @description Union of all SSE event payloads. The `event:` field in the SSE frame determines the payload type (see x-sse-events).
     */
    SSEEvent:
      | components["schemas"]["StepEvent"]
      | components["schemas"]["SubAgentProgressEvent"]
      | components["schemas"]["SubAgentTextEvent"]
      | components["schemas"]["TaskSnapshotEvent"]
      | components["schemas"]["AgentQuestionEvent"]
      | components["schemas"]["FileCreatedEvent"]
      | components["schemas"]["StreamDoneEvent"];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_check_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  list_chats_api_v1_chats_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header: {
        "X-Rossum-Token": string;
        "X-Rossum-Api-Url": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_chat_api_v1_chats_post: {
    parameters: {
      query?: never;
      header: {
        "X-Rossum-Token": string;
        "X-Rossum-Api-Url": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["CreateChatRequest"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_chat_api_v1_chats__chat_id__get: {
    parameters: {
      query?: never;
      header: {
        "X-Rossum-Token": string;
        "X-Rossum-Api-Url": string;
      };
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatDetail"];
        };
      };
      /** @description Chat not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_chat_api_v1_chats__chat_id__delete: {
    parameters: {
      query?: never;
      header: {
        "X-Rossum-Token": string;
        "X-Rossum-Api-Url": string;
      };
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeleteResponse"];
        };
      };
      /** @description Chat not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_chat_commits_api_v1_chats__chat_id__commits_get: {
    parameters: {
      query?: never;
      header: {
        "X-Rossum-Token": string;
        "X-Rossum-Api-Url": string;
      };
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommitListResponse"];
        };
      };
      /** @description Chat not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_feedback_api_v1_chats__chat_id__feedback_get: {
    parameters: {
      query?: never;
      header: {
        "X-Rossum-Token": string;
        "X-Rossum-Api-Url": string;
      };
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackListResponse"];
        };
      };
      /** @description Chat not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_feedback_api_v1_chats__chat_id__feedback_put: {
    parameters: {
      query?: never;
      header: {
        "X-Rossum-Token": string;
        "X-Rossum-Api-Url": string;
      };
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeedbackRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackResponse"];
        };
      };
      /** @description Chat not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_feedback_api_v1_chats__chat_id__feedback__turn_index__delete: {
    parameters: {
      query?: never;
      header: {
        "X-Rossum-Token": string;
        "X-Rossum-Api-Url": string;
      };
      path: {
        chat_id: string;
        turn_index: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeleteResponse"];
        };
      };
      /** @description Chat not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  send_message_api_v1_chats__chat_id__messages_post: {
    parameters: {
      query?: never;
      header: {
        "X-Rossum-Token": string;
        "X-Rossum-Api-Url": string;
      };
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MessageRequest"];
      };
    };
    responses: {
      /** @description SSE stream of agent events. Each SSE message has an `event:` field (one of: step, sub_agent_progress, sub_agent_text, task_snapshot, agent_question, file_created, done) and a `data:` field containing the JSON-serialized event payload. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": components["schemas"]["SSEEvent"];
        };
      };
      /** @description Chat not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Rate limit exceeded */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  cancel_message_api_v1_chats__chat_id__cancel_post: {
    parameters: {
      query?: never;
      header: {
        "X-Rossum-Token": string;
        "X-Rossum-Api-Url": string;
      };
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancellation result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CancelResponse"];
        };
      };
      /** @description Chat not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_commands_api_v1_commands_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommandListResponse"];
        };
      };
    };
  };
  list_files_api_v1_chats__chat_id__files_get: {
    parameters: {
      query?: never;
      header: {
        "X-Rossum-Token": string;
        "X-Rossum-Api-Url": string;
      };
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FileListResponse"];
        };
      };
      /** @description Chat not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  download_file_api_v1_chats__chat_id__files__filename__get: {
    parameters: {
      query?: never;
      header: {
        "X-Rossum-Token": string;
        "X-Rossum-Api-Url": string;
      };
      path: {
        chat_id: string;
        filename: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Invalid filename */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Chat or file not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  report_to_slack_api_v1_chats__chat_id__report_to_slack_post: {
    parameters: {
      query?: never;
      header: {
        "X-Rossum-Token": string;
        "X-Rossum-Api-Url": string;
      };
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json":
          | components["schemas"]["ReportToSlackRequest"]
          | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportToSlackResponse"];
        };
      };
      /** @description Chat not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Slack integration not installed */
      501: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Slack service error */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Slack not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
